Dharma_App/Dharma_App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),

    path('', include('login.urls')),
    path('', include('cart.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dharma_App/cart/urls.py
from django.urls import path
from . import views
from .views import ProductList, AddProduct, DeleteProduct, EditProduct

app_name = 'cart'  # Define the namespace for the cart app

urlpatterns = [
    path('productlist', ProductList.as_view(), name='productlist'),
    path('addproduct/', AddProduct.as_view(), name='addproduct'),
    path('editproduct/<int:id>', EditProduct.as_view(), name='editproduct'),
    path('deleteproduct/', DeleteProduct.as_view(), name='deleteproduct'),
    path('searchproduct', views.searchproduct, name='searchproduct'),
    path('dashboard_base', views.dashboard_base, name='dashboard_base'),
    path('seller_dashboard', views.seller_dashboard, name='seller_dashboard'),
    path('seller_addproduct', views.seller_addproduct, name='seller_addproduct'),
    path('seller_manageproduct', views.seller_manageproduct, name='seller_manageproduct'),
    path('product_detailpage', views.product_detailpage, name='product_detailpage'),
]

Dharma_App/cart/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#
# Product Model for Items to buy/sell
class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=144)
    PRODUCT_TYPE_CHOICES = [
        ('', '--- Your Product Falls Under Which Type? ---'),
        ('Package', 'Package'),
        ('Product', 'Product'),
    ]
    product_type = models.CharField(max_length=144, choices=PRODUCT_TYPE_CHOICES)
    PRODUCT_CATEGORY_CHOICES = [
        ('', '--- Your Product Falls Under Which Type? ---'),
        ('Category1', 'Category1'),
        ('Category2', 'Category2'),
        ('Category3', 'Category3'),
        ('Category4', 'Category4'),
        ('Category5', 'Category5'),
    ]
    product_category = models.TextField(max_length=144, choices=PRODUCT_CATEGORY_CHOICES)
    product_description = models.CharField(max_length=144)
    product_quantity = models.IntegerField()
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    product_stock = models.BooleanField()
    product_location = models.CharField(max_length=100)

    def __str__(self):
        return self.product_name

Dharma_App/cart/forms.py
from django import forms
from .models import Product

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'product_name', 'product_type', 'product_category', 'product_description', 'product_quantity', 'product_price', 'product_location', 'product_stock']

Dharma_App/cart/views.py
from django.shortcuts import render, redirect
from .models import User, Product
from django.views import View
from .forms import AddProductForm
from django.contrib import messages
from django.db.models import Q

# Create your views here.
# Function based method
# def productlist(request):
#     current_user = request.user  # Since we are using Django's built-in authentication system, we request the current user associated to product

#     products = Product.objects.filter(seller=current_user) # User associated to their particular product

#     return render (request, 'cart/productlist.html', {'products': products, 'user': current_user})

# Class based method
class ProductList(View):
    def get(self, request):
        current_user = request.user  # Since we are using Django's built-in authentication system, we request the current user associated to product

        products = Product.objects.filter(seller=current_user) # User associated to their particular product

        return render (request, 'cart/productlist.html', {'products': products, 'user': current_user})
    
class AddProduct(View):
    def get(self, request):
        productform = AddProductForm()
        return render (request, 'cart/addproduct.html', {
            'form': productform
        })
    
    def post(self, request):
        productform = AddProductForm(request.POST)
        # print(productform)
        if productform.is_valid():
            # productform.save()
            obj = productform.save(commit=False)
            obj.seller = request.user
            obj.save()
            messages.success(request, "Product Added Successfully")
            return redirect('cart:productlist')

        else:
            messages.error(request, "Sorry, An Error Occured")
            return render(request, 'cart/addproduct.html', {
                'form': productform
            })
        
class DeleteProduct(View):
    def post(self, request):
        data = request.POST
        # print(data)
        id = data.get('id')
        # print(id)
        productdata = Product.objects.get(id=id)
        # print(productdata)
        productdata.delete()
        messages.error(request, "Data Deleted Successfully")
        return redirect('cart:productlist')
    
class EditProduct(View):
    def get(self, request, id):
        # print(id)
        productdata = Product.objects.get(id=id)
        productform = AddProductForm(instance=productdata)
        return render(request, 'cart/editproduct.html', {
            'form': productform
        })
    
    def post(self, request, id):
        productdata = Product.objects.get(id=id)
        productform = AddProductForm(request.POST, instance=productdata)
        if productform.is_valid():
            productform.save()
            messages.error(request, "Data Edited Successfully")
            return redirect('cart:productlist')
        
def searchproduct(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        searched_products = Product.objects.filter(Q(product_name__icontains=searched) | Q(product_location__icontains=searched))

        return render(request, 'cart/search.html', {
            'searched': searched,
            'products': searched_products,
    })

    else:
        return render(request, 'cart/search.html', {

        })
    
def dashboard_base(request):
    return render(request, 'cart/dashboard_base.html')

def seller_dashboard(request):
    return render(request, 'cart/dashboard.html')

def seller_addproduct(request):
    return render(request, 'cart/dashboard_addproduct.html')

def seller_manageproduct(request):
    return render(request, 'cart/dashboard_manageproduct.html')

def product_detailpage(request):
    return render(request, 'cart/product_detail.html')

Dharma_App/cart/templates/cart/addproduct.html
{% extends 'login/base.html' %}

{% block body_block %}
{% load static %}

<div class="container mt-5 pt-5">
    <div class="d-flex justify-content-center text-center align-items-center h-100">
        <div class="container">
            <div class="mb-5" style="width: fit-content; margin: auto;">
                <h1 class="display-4 fw-bold">Add New Product</h1>
                <hr class="border border-secondary border-2 opacity-100 rounded-5">
            </div>
        </div>
    </div>
</div>

<div class="container mb-5">
    <form method="POST" action="">

        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">Submit</button>

    </form>
</div>

{% endblock %}

Dharma_App/cart/templates/cart/dashboard.html
{% extends 'cart/dashboard_base.html' %}
{% block content_block %}
{% load static %}

<h3 class="fw-light">Seller Analytic Dashboard</h3>
<hr>
<div class="row">
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading fw-bold">Total Orders</div>
                        <div class="widget-subheading">Monthly Orders</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-success">100</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading fw-bold">Total Orders</div>
                        <div class="widget-subheading">Yearly Orders</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-success">1000</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading fw-bold">Total Profit</div>
                        <div class="widget-subheading">Yearly Profit</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-success">$ 10000</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading fw-bold">Product Sold</div>
                        <div class="widget-subheading">Product Count Montly</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-success">99</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-xl-4">
        <div class="card mb-3 widget-content">
            <div class="widget-content-outer">
                <div class="widget-content-wrapper">
                    <div class="widget-content-left">
                        <div class="widget-heading fw-bold">Product Sold</div>
                        <div class="widget-subheading">Product Count Yearly</div>
                    </div>
                    <div class="widget-content-right">
                        <div class="widget-numbers text-success">999</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<h3 class="fw-light">Active Orders</h3>
<hr>
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>S.N.</th>
            <th>Name</th>
            <th>City</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>
                <p class="fw-bold mb-1">Jane Doe</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Kathmandu</p>
            </td>
            <td>
                <span class="badge text-bg-warning">Pending</span>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <button class="btn btn-primary">Details</button>
                </p>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>
                <p class="fw-bold mb-1">John Doe</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Gorkha</p>
            </td>
            <td>
                <span class="badge text-bg-danger">In Progress</span>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <button class="btn btn-primary">Details</button>
                </p>
            </td>
        </tr>
        <tr>
            <td>3</td>
            <td>
                <p class="fw-bold mb-1">Jack Doe</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Muktinath</p>
            </td>
            <td>
                <span class="badge text-bg-success">Completed</span>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <button class="btn btn-primary">Details</button>
                </p>
            </td>
        </tr>
    </tbody>
</table>

{% endblock %}

Dharma_App/cart/templates/cart/dashboard_base.html
{% extends 'login/base.html' %}
{% block body_block %}
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

<style>
    .bg-dark{
        background-color: #2E2E2E !important;
    }
    .widget-content{
        background: rgb(2,0,36);
        background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(6,51,99,1) 0%, rgba(81,55,206,1) 100%); 
    }
    .widget-content-wrapper {
        display: flex;
        justify-content: space-between;
        padding: 20px;
    }
    
    .widget-content-left {
        flex-grow: 1; /* This makes the left content take up available space */
        text-align: left;
        color: white;
    }
    
    .widget-content-right {
        text-align: right;
        color: white;
    }
    .widget-numbers {
        font-size: 35px !important;
        color: white !important;
        font-weight: bold;
    }
    
</style>

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item" id="sidebar-item-link">
                    <a href="{% url 'cart:seller_dashboard' %}" class="nav-link align-middle px-0">
                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                    </a>
                    </li>
                    <li class="nav-item" id="sidebar-item-link">
                    <a href="{% url 'cart:seller_addproduct' %}" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi bi-plus-square"></i> <span class="ms-1 d-none d-sm-inline">Add Package</span></a>
                    </li>
                    <li class="nav-item" id="sidebar-item-link">
                        <a href="{% url 'cart:seller_manageproduct' %}" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi bi-search"></i> <span class="ms-1 d-none d-sm-inline">Manage Package</span> </a>
                    </li>
                    <li class="nav-item" id="sidebar-item-link">
                        <a href="#" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Order</span></a>
                    </li>
                    <li class="nav-item" id="sidebar-item-link">
                        <a href="#" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi bi-clock-history"></i> <span class="ms-1 d-none d-sm-inline">History</span> </a>
                    </li>
                    <!-- <li class="nav-item" id="sidebar-item-link">
                        <a href="#" class="nav-link px-0 align-middle">
                        <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
                    </li> -->
                </ul>
            </div>
        </div>
        <div class="col py-3">
            {% block content_block %}
            {% endblock %}
        </div>
    </div>
</div>
 
                        
{% endblock %}

Dharma_App/cart/templates/cart/dashboard_manageproduct.html
{% extends 'cart/dashboard_base.html' %}
{% block content_block %}
{% load static %}

<div class="heading-container text-center my-2">
    <h1 class="display-6 fw-bold">Manage Package</h1>
</div>

<h3 class="fw-light">All of your Packages</h3>
<hr>
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>S.N.</th>
            <th>Package Name</th>
            <th>City</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>
                <p class="fw-bold mb-1">Package 1</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Holy Place 1</p>
            </td>
            <td>
                <p class="fw-normal mb-1">$ 100</p>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <a href="{% url 'cart:product_detailpage' %}"><button class="btn btn-primary">Manage</button></a>
                </p>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>
                <p class="fw-bold mb-1">Package 2</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Holy Place 2</p>
            </td>
            <td>
                <p class="fw-normal mb-1">$ 200</p>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <a href="{% url 'cart:product_detailpage' %}"><button class="btn btn-primary">Manage</button></a>
                </p>
            </td>
        </tr>
        <tr>
            <td>3</td>
            <td>
                <p class="fw-bold mb-1">Package 3</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Holy Place 3</p>
            </td>
            <td>
                <p class="fw-normal mb-1">$ 300</p>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <a href="{% url 'cart:product_detailpage' %}"><button class="btn btn-primary">Manage</button></a>
                </p>
            </td>
        </tr>
        <tr>
            <td>3</td>
            <td>
                <p class="fw-bold mb-1">Package 4</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Holy Place 4</p>
            </td>
            <td>
                <p class="fw-normal mb-1">$ 400</p>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <a href="{% url 'cart:product_detailpage' %}"><button class="btn btn-primary">Manage</button></a>
                </p>
            </td>
        </tr>
        <tr>
            <td>3</td>
            <td>
                <p class="fw-bold mb-1">Package 5</p>
            </td>
            <td>
                <p class="fw-normal mb-1">Holy Place 5</p>
            </td>
            <td>
                <p class="fw-normal mb-1">$ 500</p>
            </td>
            <td>
                <p class="fw-normal mb-1">
                    <a href="{% url 'cart:product_detailpage' %}"><button class="btn btn-primary">Manage</button></a>
                </p>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

Dharma_App/cart/templates/cart/editproduct.html
{% extends 'login/base.html' %}
{% block body_block %}

{% load static %}

<div class="container mt-5 pt-5">
    <div class="d-flex justify-content-center text-center align-items-center h-100">
        <div class="container">
            <div class="mb-5" style="width: fit-content; margin: auto;">
                <h1 class="display-4 fw-bold">Edit Product</h1>
                <hr class="border border-secondary border-2 opacity-100 rounded-5">
            </div>
        </div>
    </div>
</div>

<div class="container mb-5">
    <form method="POST">

        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">Submit</button>

    </form>
</div>

{% endblock %}

Dharma_App/cart/templates/cart/productlist.html
{% extends 'login/base.html' %}
{% block body_block %}

{% load static %}

<style>
    .scroll-custom {
        width: 100%;
        overflow-x: auto;
        overflow-y: hidden;
        white-space: nowrap;
    }

    /* Custom CSS for responsive input group */
    .search-bar-width {
        width: 100%; /* Default width for all screen sizes */
    }

    /* Medium to large screens (greater than 768px) */
    @media (min-width: 768px) {
        .search-bar-width {
            width: 25%; /* Adjust as needed */
        }
    }

    /* Small screens (up to 767px) */
    @media (max-width: 767px) {
        .search-bar-width {
            width: 50%; /* Adjust as needed */
        }
    }
</style>

<div class="container mt-5 pt-5">
    <div class="d-flex justify-content-center text-center align-items-center h-100">
        <div class="container">
            <div class="mb-5" style="width: fit-content; margin: auto;">
                <h1 class="display-4 fw-bold">All Products</h1>
                <hr class="border border-secondary border-2 opacity-100 rounded-5">
            </div>
        </div>
    </div>
</div>

{% if products %}
<div class="container">
    <div class="row mb-3 d-flex justify-content-between">
        <div class="col-auto">
            <select class="form-select" aria-label="Default select example">
                <option selected>--Sort By--</option>
                <option value="1">Option 1</option>
                <option value="2">Option 2</option>
                <option value="3">Option 3</option>
            </select>
        </div>
        <div class="input-group search-bar-width">
            <div class="form-outline" data-mdb-input-init>
                <input type="search" id="form1" class="form-control" />
                <label class="form-label" for="form1">Search</label>
            </div>
            <button type="button" class="btn btn-primary" data-mdb-ripple-init>
                <i class="fas fa-search"></i>
            </button>
        </div>
             
    </div>
    <a href="{% url 'cart:addproduct' %}"><button class="btn btn-outline-primary w-100 mb-3">Add Product</button></a>    
</div>

<div class="container mb-5 scroll-custom px-0 rounded shadow">
    
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
            <tr>
                <th>S.N.</th>
                <th>Name</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Stock</th>
                <th>Category</th>
                <th>Type</th>
                <th>Location</th>
                <th>Seller</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <div class="d-flex align-items-center">
                        <img
                        src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                        alt=""
                        style="width: 45px; height: 45px"
                        class="rounded-circle"
                        />
                        <div class="ms-3">
                            <p class="fw-bold mb-1">{{ product.product_name }}</p>
                        </div>
                    </div>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{ product.product_description }}</p>
                </td>
                <td>
                    <span class="badge badge-success rounded-pill d-inline">{{ product.product_quantity }}</span>
                </td>
                <td>
                    <p class="fw-normal mb-1">
                        <!-- {{ product.product_stock }} -->
                        {% if product.product_stock == True %}
                        <i class="fa-solid fa-check fa-xl" style="color: #3AB54A;"></i>
                        <!-- <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" />
                        </div> -->
                        
                        {% else %}
                        <i class="fa-regular fa-circle-xmark fa-xl" style="color: #ED1B24"></i>
                        <!-- <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" />
                        </div> -->
                        {% endif %}
                    </p>
                </td>
                <td>
                    <span class="badge badge-success rounded-pill d-inline">{{ product.product_category }}</span>
                </td>
                <td>
                    <span class="badge badge-success rounded-pill d-inline">{{ product.product_type }}</span>
                </td>
                <td>
                    <p class="fw-bold mb-1">{{ product.product_location }}</p>
                </td>
                <td>
                    
                    <div class="d-flex align-items-center">
                        <img
                        src="https://mdbootstrap.com/img/new/avatars/8.jpg"
                        alt=""
                        style="width: 45px; height: 45px"
                        class="rounded-circle"
                        />
                        <div class="ms-3">
                            <p class="fw-bold mb-1">{{ user.username }}</p>
                            <p class="text-muted mb-0">{{ user.email }}</p>
                        </div>
                    </div>
                    
                </td>
                <td>
                    <a href="{% url 'cart:editproduct' product.id %}" class="btn btn-outline-primary">Edit</a>
                </td>
                <td>
                    <form method="POST" action="{% url 'cart:deleteproduct' %}">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ product.id }}">
                        <input value="Delete" type="submit" class="btn btn-outline-primary"> 
                    </form>
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
{% else %}
<div class="container text-center">
    <i class="fa-regular fa-face-frown-open fa-2xl me-2"></i><i class="fa-solid fa-question fa-bounce fa-2xl"></i>
    <h1 class="display-6 mt-3">No Records Added Yet</h1>
    <a href="{% url 'cart:addproduct' %}"><button class="btn btn-primary rounded-pill">Add Product</button></a>
</div>
{% endif %}

{% endblock %}

Dharma_App/cart/templates/cart/search.html
{% extends 'login/base.html' %}
{% block body_block %}

{% load static %}

{% if searched %}
    <div class="container mt-5 pt-5 mb-5">
        <div class="d-flex justify-content-center text-center align-items-center h-100">
            <div class="container">
                <div class="mb-5" style="width: fit-content; margin: auto;">
                    <h1 class="display-6 fw-bold">All Results For: " {{ searched }} "</h1>
                    <hr class="border border-secondary border-2 opacity-100 rounded-5">
                </div>

                {% for product in products %}
                <a href="/"><p>{{ product.product_name }} - {{ product.product_location }}</p></a>
                {% endfor %}

            </div>
        </div>
    </div>

{% else %}

    <div class="container mt-5 pt-5">
        <div class="d-flex justify-content-center text-center align-items-center h-100">
            <div class="container">
                <div class="mb-5" style="width: fit-content; margin: auto;">
                    <h1 class="display-6 fw-bold">Search Something First</h1>
                    <hr class="border border-secondary border-2 opacity-100 rounded-5">
                </div>
            </div>
        </div>
    </div>

{% endif %}



{% endblock %}